"""Initial migration.

Revision ID: e2895de74d25
Revises: 
Create Date: 2022-04-18 02:30:27.868393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2895de74d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserBasic',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hash_password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('deactivate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('UserAdvance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('user_basic_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_basic_id'], ['UserBasic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserAdvance')
    op.drop_table('UserBasic')
    # ### end Alembic commands ###
